#!/bin/bash

YAKKO=$1
OC=$2

wait-for-operators-active() {

	[ -n "$1" ] && sleep $1

	TOTALOPS=$($OC get co | grep -v NAME -c)

	echo -n Waiting for all operators to become available

	while true
	do
		WORKINGOPS=$($OC get co 2>/dev/null | awk '{ print $3}' | grep -c True 2>/dev/null )

		if [ $(( $TOTALOPS - $WORKINGOPS )) -eq 0 ]
		then
			break
		else
			sleep 10
			echo -n .
			continue
		fi
	done
	echo
}

$YAKKO ops localregistry Y
wait-for-operators-active

$YAKKO ops yakkotest
wait-for-operators-active

$OC scale deployment yakko --replicas=5
