#!/bin/bash

which oc &>/dev/null
if [ $? -ne 0 ]
then 
	echo "ERROR: Cannot continue, no oc client!"
	exit
fi

if [ -x ./cluster-login ]
then 
	./cluster-login
else
	oc login --username=kubeadmin
fi

oc new-project pacman
oc new-app --image=quay.io/rhn_sa_dcifuent/pacman:v2

echo
echo "Waiting for container pacman to enter 'Running' mode..."
while true
do
	oc get pods 2>/dev/null | grep pacman | grep Running &>/dev/null
	[ $? -eq 0 ] && break
done

oc expose service/pacman
ROUTE=$(oc get route | grep pacman | awk '{ print $2 }')
echo
echo "Pacman should now be running at http://$ROUTE"
echo "But note - only the game - no DB for high scores!"
echo

